version: '3'
services:
  postgress:
  
  backend:
    build:
      dockerfile: ./server-for-react-app/Dockerfile
    ports:
      - "3000:3000"
    restart:  always
  frontend:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - backend